fix: ファイル名にスラッシュが含まれるときのバグを修正
weakboson/doujin-scraper pull request #14
Opened 2021-04-18 00:47 UTC by nasu-no-suage

ファイル名やサークル名にスラッシュが含まれるとファイル名の制約よりエラーが発生しました。スラッシュを分数スラッシュに変更してバグを修正しました。
ただ、利用者が使っているフォントによってはスラッシュの部分が文字化けするかもしれません。
置き換える先の文字は他にもあると思いますが、暫定として分数スラッシュとしました。

## エラーが起きた環境
ArchLinux 
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]

## エラー

```
bash bin/rename-dmm.sh

Creating doujin-scraper_ruby_run ... done
/usr/local/lib/ruby/2.7.0/fileutils.rb:548:in `rename': No such file or directory @ rb_file_s_rename - (/app/downloads/d_133171.zip, /app/downloads/[禁断童話] 昭和44年夏、脱.包茎！/脱.童貞！.zip) (Errno::ENOENT)
        from /usr/local/lib/ruby/2.7.0/fileutils.rb:548:in `block in mv'
        from /usr/local/lib/ruby/2.7.0/fileutils.rb:1588:in `block in fu_each_src_dest'
        from /usr/local/lib/ruby/2.7.0/fileutils.rb:1604:in `fu_each_src_dest0'
        from /usr/local/lib/ruby/2.7.0/fileutils.rb:1586:in `fu_each_src_dest'
        from /usr/local/lib/ruby/2.7.0/fileutils.rb:539:in `mv'
        from bin/rename_dlfile.rb:10:in `block in <main>'
        from bin/rename_dlfile.rb:6:in `each'
        from bin/rename_dlfile.rb:6:in `<main>'
ERROR: 1
```
## エラーの原因
修正前9行目
`
  FileUtils.mv(org, File.join(BASEDIR, "#{basename}.zip")) if File.file?(org)
`
でFile.join(...)で文字列中の/はエスケープされずそのままディレクトリの構造だと認識され、存在しないフォルダが存在していると認識されます。
この場合実際は
`[禁断童話] 昭和44年夏、脱.包茎！/脱.童貞！.zip`
というファイルを作りたいのですが誤認識で`[禁断童話] 昭和44年夏、脱.包茎！`というフォルダが存在することになります。実際はそのようなフォルダは存在しないので存在しないフォルダ内にFileUtils.mv(...)でファイルをmvしようとしてエラーが起きます。

## エラーが出る作品例
### タイトルに"/"が入っている場合
[禁断童話]昭和44年夏、脱.包茎！/脱.童貞！
https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_133171/
### サークル名に"/"が入っている場合
[ボウテンムスビ/溺愛信仰]巨乳妻たちはレンタル彼氏にハメられて！ 専業主婦、OL上司、ヤンママが…
https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_158044/

レビューをお願いします。

2021-04-19 05:57 UTC, nasu-no-suage commented
gitに不慣れなものでコミットがごちゃごちゃしてますが
実質的な変化は最後のコミット e2f8c09 だけです。

2021-04-19 15:55 UTC, weakboson requested changes
- 文字の置換処理をコメントのように拡張しやすくするともっと良くなると思います
- `git rebase -i` で squash などして、間違い commit は消して欲しいです

2021-04-19 15:55 UTC, weakboson commented on bin/rename_dlfile.rb
> +  basename.gsub!(%r{\/}, "\u2044") # フォワードスラッシュの代わりに分数スラッシュを使用
以下の対応ができるともっと良くなると思います。

OS により異なりますが `/` 同様にファイル名として使えない文字があります。
「利用できない、または利用しない方がよい文字」と「置換先」の Hash を元に変換するメソッドを定義して利用するとスマートだと思います。
本 Pull request ではとりあえず `/` だけでも良くて、後々 `\0` とか `:` のような文字も置換したくなったとき Hash の修正で対応できるようになります。

2021-04-20 08:50 UTC, nasu-no-suage commented on bin/rename_dlfile.rb
> +  basename.gsub!(%r{\/}, "\u2044") # フォワードスラッシュの代わりに分数スラッシュを使用
commitの件大変失礼いたしました。
間違いcommitはすべて消しました。

またご提案通りメソッドを作りその中でHashをeachメソッドを用いて使えない文字を一文字ずつ置換していくようにしました。

レビューをよろしくお願いします。

2021-04-20 17:12 UTC, weakboson requested changes
Ruby の慣例的でないコードだったのでコメントしました。

2021-04-20 17:12 UTC, weakboson commented on bin/rename_dlfile.rb
- special_letters は定数にして substitute_special_letters メソッドは定数を参照するのがよいでしょう
- special_letters にペアが追加されたときうまく動かないような気がします
each は Hash の key, value をブロック変数でとれるので gsub の第一、第二引数を each の key, value にすると良いはずです
- Ruby では省略できる return は省略する方が通例です（特にメソッドの最後の戻り値）
- 好み次第ですが `gsub` のレシーバを変更する破壊的メソッド版 `gsub!` を使うと再代入の繰り返しを避けられます。（ホントに好み次第ですが）引数をレシーバにそのまま使うと引数を変更してしまうので `dup` と組み合わせるのが定番です

指摘を合わせるとこんな具合になります。（変数、引数名は適当に短縮したりしてます。）

```rb
SPECIAL_LETTERS_MAP = {
  "/" => "\u2044",
  ":" => "：" # 例えばコロンも対応するとしたら
}
def substitute_special_letters(original)
  sub_name = original.dup
  SPECIAL_LETTERS_MAP.each do |k, v|
    sub_name.gsub!(k, v)
  end
  sub_name
end
```

2021-04-20 17:12 UTC, weakboson commented on bin/rename_dlfile.rb
>    FileUtils.mv(org, File.join(BASEDIR, "#{basename}.zip")) if File.file?(org)
```suggestion
  FileUtils.mv(org, File.join(BASEDIR, "#{substitute_special_letters(basename)}.zip")) if File.file?(org)
```
引数1つのメソッドになったらインターポレーションの中で変換してもよいくらいかなと思います。

2021-04-21 05:41 UTC, nasu-no-suage commented on bin/rename_dlfile.rb
レビューありがとうございます。
@weakboson さんの言うとおりに修正しました。

2021-04-21 05:42 UTC, nasu-no-suage commented on bin/rename_dlfile.rb
>    FileUtils.mv(org, File.join(BASEDIR, "#{basename}.zip")) if File.file?(org)
レビューありがとうございます。
ここのコードも提案通りそのまま修正しました。

2021-04-21 16:23 UTC, weakboson approved these changes
ミス commit ではないレビュー指摘修正の commit は rebase しなくてもよいかなーと思います。
LGTM です。

2021-04-21 16:23 UTC, merged